#  cuestionario_manejo_errores.py

# Pregunta 1:
# ¿En qué momento se puede usar try-except?
#  Respuesta: Al capturar un error.

# Pregunta 2:
# Selecciona la afirmación incorrecta:
#  Respuesta: El código dentro de except se ejecuta incluso cuando no hay error en el código dentro de try.

# Pregunta 3:
# Sumar un número a una cadena produce un TypeError. ¿Qué imprimirá el código?
#  Respuesta: No se puede sumar un número a una cadena.

# Pregunta 4:
# ¿Qué producirá el siguiente código sin try-except?
#  Respuesta: Traceback (última llamada más reciente)... TypeError: solo se puede concatenar str (no "int") a str
